patreon: Daffa Noorfridan
open_collective: daffa-noorfridan
ko_fi: Ko-fi.com/daffanoorfridan
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: https://oss.issuehunt.io/u/daffa-noorfridan
lfx_crowdfunding: https://openprofile.dev/profile/daffanoorfridan
polar: # Replace with a single Polar username
buy_me_a_coffee: https://buymeacoffee.com/daffanoorfridan
thanks_dev: gh/daffa-noorfridan
custom: https://wa.me/6282126168973
